added age api and added class group field in class section
kishoreecampus/ecampus pull request #15
Opened 2021-03-23 16:50 UTC by krishnakanth12

please lookout and let me know any changes

2021-03-25 15:08 UTC, kishoreecampus requested changes

2021-03-25 15:08 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/models.py
> +    age = models.IntegerField('age',validators=[age_validator])
remove age field and add from_age and to_age field.

2021-03-25 15:08 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/urls.py
> +    path('age/delete/<pk>/',AgeViewset.as_view({'delete': 'destroy'}), name='delete_age'),
Need one more API get class between given age. i.e Given age 5 and find class for the age.

2021-03-25 15:08 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/views.py
> +    def perform_create(self, serializer):
Condition Not required, only authenticated user will have access.

2021-04-02 18:05 UTC, kishoreecampus requested changes

2021-04-02 18:05 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
>          fields = ['category', 'created_on']
Remove created_on

2021-04-02 18:05 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
>  class CategorySerializer(serializers.ModelSerializer):
Check this

2021-04-02 18:05 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +class Anonymous_ClassNameDetailSerializer(serializers.ModelSerializer):
Change Name

2021-04-02 18:05 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/views.py
> +            user = 0
Remove sapce

2021-04-02 18:20 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
>  class CategorySerializer(serializers.ModelSerializer):
yeah ajith Raghavendra sir asked us to get class group also in class section also

2021-04-02 18:27 UTC, kishoreecampus approved these changes

2021-04-02 18:27 UTC, merged