Removed unnecessary validation
kishoreecampus/ecampus pull request #9
Opened 2021-03-01 14:52 UTC by krishnakanth12

Master API- Modified to allow some special characters in-class group, class name, class sections

2021-03-01 15:16 UTC, kishoreecampus requested changes

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +        return validated_data
Remove this and use Unique attribute in model level.

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('phone number already exist.')
Remove this and use model validation

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class group name")
Remove this and use model validation

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('class group already exist.')
Remove this and use model validation

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('class name already exist.')
Remove this and use model validation

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class name")
use isalpha function

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class name")
Check on this.

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid section name")
Check on this

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('Category already exists')
Use unique attribute

2021-03-01 15:16 UTC, kishoreecampus commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('Category already exists')
Use unique

2021-03-02 08:30 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +        return validated_data
removed please look out in models

2021-03-02 08:31 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('phone number already exist.')
removed

2021-03-02 08:31 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class group name")
removed

2021-03-02 08:31 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('class group already exist.')
removed

2021-03-02 08:31 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('class name already exist.')
removed

2021-03-02 08:32 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class name")
as discussed created a custom regex validator

2021-03-02 08:32 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid class name")
done

2021-03-02 08:32 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError("Invalid section name")
removed

2021-03-02 08:32 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('Category already exists')
yeah created in models

2021-03-02 08:33 UTC, krishnakanth12 commented on eCampusAPI/ecampus_api/master/serializers.py
> +            raise serializers.ValidationError('Category already exists')
yeah created please look out models

2021-03-02 15:34 UTC, kishoreecampus approved these changes

2021-03-02 15:34 UTC, merged